# Generated by Django 5.2.14 on 2026-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginactivity_logout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='currency',
            field=models.CharField(default='NPR', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='fiscal_year_start',
            field=models.CharField(default='07-16', help_text='MM-DD, Nepal fiscal year starts mid-July', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
