# Generated by Django 5.2.14 on 2026-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode_code_hash_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
    ]
