# Generated by Django 5.2.14 on 2026-08-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=13, help_text='Default VAT % applied to new sales/purchases, e.g. 13', max_digits=5),
        ),
    ]
