# Generated by Django 5.2.14 on 2026-08-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_business_default_tax_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'businesses'},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['joined_at']},
        ),
    ]
