# Generated by Django 5.2.14 on 2026-08-23 04:01

from django.db import migrations, models


def blank_phones_to_null(apps, schema_editor):
    # Every existing row currently has phone="" (nothing has ever written to
    # this field before now) — the new unique=True constraint below would
    # reject the second such row as a duplicate of the first, since an empty
    # string is a real, unique-checkable value, unlike NULL.
    User = apps.get_model("accounts", "User")
    User.objects.filter(phone="").update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_business_options_alter_staffmember_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(blank_phones_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
