# Generated by Django 5.2.14 on 2026-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_phone_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='staff_limit_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_limit_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
