# Generated by Django 5.2.14 on 2026-08-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_business_staff_limit_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='mobile_trial_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='mobile_trial_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='mobile_trial_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='web_trial_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='web_trial_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='web_trial_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
