# Generated by Django 5.2.14 on 2026-09-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_phone_signup_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='login_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
