# Generated by Django 5.2.14 on 2026-09-07 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staffmember_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('PREMIUMPLUS', 'Premium Plus')], default='FREE', max_length=20),
        ),
    ]
