# Generated by Django 6.1.1 on 2026-09-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_fiscalyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
