# Generated by Django 5.2.14 on 2026-09-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
