# Generated by Django 5.2.14 on 2026-09-22 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_loginactivity_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffactivity',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'staff activities'},
        ),
        migrations.AddField(
            model_name='staffactivity',
            name='new_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='staffactivity',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffactivity',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffactivity',
            name='object_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffactivity',
            name='old_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='staffactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='staffactivity',
            index=models.Index(fields=['business', '-timestamp'], name='accounts_st_busines_e03947_idx'),
        ),
    ]
