# Generated by Django 6.1.1 on 2026-09-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_staffactivity_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superadmin_unlocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
