# Generated by Django 5.2.14 on 2026-10-08 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_superadmin_unlocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('PARTNER', 'Business Partner'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('SALESPERSON', 'Salesperson'), ('CASHIER', 'Cashier'), ('ENTRY', 'Entry Person'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('VIEWER', 'Viewer')], default='CASHIER', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('PARTNER', 'Business Partner'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('SALESPERSON', 'Salesperson'), ('CASHIER', 'Cashier'), ('ENTRY', 'Entry Person'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('VIEWER', 'Viewer')], default='CASHIER', max_length=20)),
                ('permissions', models.JSONField(default=dict)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='accounts.business')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
