# Generated by Django 5.2.14 on 2026-08-30 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_business_mobile_trial_enabled_and_more'),
        ('superadmin', '0004_license_licenseauditlog_businessfeatureoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('DELETED', 'Deleted')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('object_repr', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.business')),
                ('user', models.ForeignKey(blank=True, help_text='Who performed the action — null when the underlying model has no created_by field.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='superadmin__busines_c0757e_idx')],
            },
        ),
    ]
