# Generated by Django 5.2.14 on 2026-08-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='duration_type',
            field=models.CharField(choices=[('7D', '7 Days'), ('30D', '30 Days'), ('1Y', '1 Year'), ('5Y', '5 Years'), ('LIFETIME', 'Lifetime'), ('CUSTOM', 'Custom')], max_length=10),
        ),
    ]
