# Generated by Django 5.2.14 on 2026-06-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='purchases/bills/'),
        ),
    ]
