# Generated by Django 5.2.14 on 2026-08-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchase_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reconciled_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portion of paid_amount applied here later via a party PartyPayment (see PartyPaymentListCreateView._reconcile_payment), as opposed to being paid at the point of purchase. Lets the party ledger show each rupee exactly once instead of double-counting reconciled payments.', max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT % e.g. 13', max_digits=5),
        ),
    ]
