# Generated by Django 5.2.14 on 2026-08-10 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_update_bankaccount_type_choices'),
        ('purchases', '0004_purchase_reconciled_amount_purchase_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Which account paid_amount was paid from when payment_method is non-cash — a matching BankTransaction is kept in sync automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='banking.bankaccount'),
        ),
    ]
