# Generated by Django 5.2.14 on 2026-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_backfill_base_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash portion of paid_amount when payment_method is SPLIT — the remainder (paid_amount - cash_amount) is paid from bank_account instead. Unused (0) for every other payment method.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('SPLIT', 'Split (Cash + Bank)')], default='CASH', max_length=10),
        ),
    ]
