# Generated by Django 5.2.14 on 2026-09-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_bankaccount_deleted_at_bankaccount_is_deleted_and_more'),
        ('purchases', '0009_purchasereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Which account received the refund when refund_method is BANK.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_refunds', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='refund_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
