# Generated by Django 5.2.14 on 2026-09-07 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_business_referral_code_business_referred_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=6, unique=True)),
                ('plan', models.CharField(choices=[('PREMIUM', 'Premium'), ('PREMIUMPLUS', 'Premium Plus')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ADMIN', 'Admin'), ('REFERRAL', 'Referral')], default='ADMIN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_created', to=settings.AUTH_USER_MODEL)),
                ('used_for_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_redeemed', to='accounts.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('PREMIUM', 'Premium'), ('PREMIUMPLUS', 'Premium Plus')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source', models.CharField(choices=[('ADMIN', 'Admin'), ('REFERRAL', 'Referral')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.business')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLICKED', 'Clicked'), ('REGISTERED', 'Registered'), ('VERIFIED', 'Verified'), ('REWARDED', 'Rewarded'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='REGISTERED', max_length=20)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('referred_business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_via', to='accounts.business')),
                ('referrer_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='accounts.business')),
                ('referred_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription')),
                ('referrer_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
