import { api } from "./client";
export const authApi={requestOtp:(p)=>api.post("/auth/request-otp",p),verifyOtp:(p)=>api.post("/auth/verify-otp",p),me:()=>api.get("/auth/me"),logout:()=>api.post("/auth/logout")};
export const dashboardApi={get:()=>api.get("/dashboard")};
export const partiesApi={list:()=>api.get("/parties"),create:(p)=>api.post("/parties",p),remove:(id)=>api.delete(`/parties/${id}`),ledger:(id)=>api.get(`/parties/${id}/ledger`)};
export const itemsApi={list:()=>api.get("/items"),create:(p)=>api.post("/items",p),remove:(id)=>api.delete(`/items/${id}`)};
export const salesApi={list:()=>api.get("/sales"),create:(p)=>api.post("/sales",p),remove:(id)=>api.delete(`/sales/${id}`)};
export const purchasesApi={list:()=>api.get("/purchases"),create:(p)=>api.post("/purchases",p),remove:(id)=>api.delete(`/purchases/${id}`)};
export const paymentsApi={list:()=>api.get("/payments"),create:(p)=>api.post("/payments",p),remove:(id)=>api.delete(`/payments/${id}`)};
export const expensesApi={list:()=>api.get("/expenses"),create:(p)=>api.post("/expenses",p),remove:(id)=>api.delete(`/expenses/${id}`)};
export const reportsApi={summary:(params={})=>api.get("/reports/summary",{params})};
export const recycleApi={list:()=>api.get("/recycle"),restore:(id)=>api.post(`/recycle/${id}/restore`),removeForever:(id)=>api.delete(`/recycle/${id}`)};
export const staffApi={list:()=>api.get("/staff"),create:(p)=>api.post("/staff",p)};
