# Generated by Django 5.2.14 on 2026-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('DISTRIBUTOR', 'Distributor'), ('RESELLER', 'Reseller')], max_length=20),
        ),
        migrations.AddField(
            model_name='party',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
