# Generated by Django 5.2.14 on 2026-06-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_party_customer_type_party_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partypayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('IME_PAY', 'IME Pay'), ('MOBILE', 'Mobile Banking')], default='CASH', max_length=10),
        ),
    ]
