# Generated by Django 5.2.14 on 2026-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_alter_partypayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='party',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
