# Generated by Django 5.2.14 on 2026-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_party_pan_number_party_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partypayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti')], default='CASH', max_length=10),
        ),
    ]
