# Generated by Django 5.2.14 on 2026-08-10 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_update_bankaccount_type_choices'),
        ('parties', '0005_alter_partypayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='partypayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Required when payment_method is a non-cash method that should hit a real account — a matching BankTransaction is kept in sync automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_payments', to='banking.bankaccount'),
        ),
    ]
