# Generated by Django 5.2.14 on 2026-08-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_paymentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='partypayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partypayment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
