# Generated by Django 5.2.14 on 2026-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='e.g. 12 means 1 Box = 12 Pieces', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='secondary_abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='secondary_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
