# Generated by Django 5.2.14 on 2026-06-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_deleted_at_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('LOST', 'Lost'), ('TRANSFER', 'Transfer'), ('OPENING', 'Opening Stock')], max_length=20),
        ),
    ]
