# Generated by Django 5.2.14 on 2026-08-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_business_status'),
        ('inventory', '0004_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], db_index=True, default='PRODUCT', help_text='PRODUCT tracks stock; SERVICE does not', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'item_type'], name='inventory_p_busines_4d7646_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_deleted'], name='inventory_p_busines_254a4a_idx'),
        ),
    ]
