# Generated by Django 5.2.14 on 2026-08-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System code — Nepal customs/VAT classification, shown on some tax invoices.', max_length=20),
        ),
    ]
