# Generated by Django 5.2.14 on 2026-08-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_hs_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name']},
        ),
    ]
