# Generated by Django 5.2.14 on 2026-08-31 15:41

from django.db import migrations


def seed_existing_businesses(apps, schema_editor):
    from inventory.defaults import DEFAULT_UNITS

    Business = apps.get_model("accounts", "Business")
    Unit = apps.get_model("inventory", "Unit")

    for business in Business.objects.all():
        existing = set(Unit.objects.filter(business=business).values_list("name", flat=True))
        Unit.objects.bulk_create([
            Unit(
                business=business,
                name=u["name"],
                abbreviation=u.get("abbreviation", ""),
                secondary_unit=u.get("secondary_unit", ""),
                secondary_abbreviation=u.get("secondary_abbreviation", ""),
                conversion_factor=u.get("conversion_factor"),
            )
            for u in DEFAULT_UNITS
            if u["name"] not in existing
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_category_options_alter_unit_options'),
    ]

    operations = [
        migrations.RunPython(seed_existing_businesses, migrations.RunPython.noop),
    ]
