# Generated by Django 5.2.14 on 2026-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('QUOTATION', 'Quotation')], default='SALE', max_length=10),
        ),
    ]
