# Generated by Django 5.2.14 on 2026-06-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_deleted_at_sale_is_deleted_sale_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CREDIT', 'Credit'), ('CHEQUE', 'Cheque'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('IME_PAY', 'IME Pay'), ('MOBILE', 'Mobile Banking')], default='CASH', max_length=10),
        ),
    ]
