# Generated by Django 5.2.14 on 2026-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT % e.g. 13', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('CHALLAN', 'Delivery Challan'), ('QUOTATION', 'Quotation')], default='SALE', max_length=10),
        ),
    ]
