# Generated by Django 5.2.14 on 2026-08-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reconciled_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portion of paid_amount applied here later via a party PartyPayment (see PartyPaymentListCreateView._reconcile_payment), as opposed to being paid at the point of sale. Lets the party ledger show each rupee exactly once instead of double-counting reconciled payments.', max_digits=14),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Snapshot of product.purchase_price at the time of sale, so editing a product's cost later doesn't retroactively rewrite past profit reports.", max_digits=12, null=True),
        ),
    ]
