# Generated by Django 5.2.14 on 2026-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_reconciled_amount_saleitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reminder_at',
            field=models.DateTimeField(blank=True, help_text='When to notify the business owner to follow up on this due amount. Fired as an on-device notification by the mobile app, not a server push.', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
