# Generated by Django 5.2.14 on 2026-08-10 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_update_bankaccount_type_choices'),
        ('sales', '0008_sale_reminder_at_sale_reminder_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Which account received paid_amount when payment_method is non-cash — a matching BankTransaction is kept in sync automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='banking.bankaccount'),
        ),
    ]
