# Generated by Django 5.2.14 on 2026-09-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_quotation_deleted_at_quotation_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='base_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
