# Generated by Django 5.2.14 on 2026-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_return_refund_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reminder_note',
            field=models.CharField(blank=True, help_text="Why this reminder was set (e.g. 'Promised to pay by Friday') — shown alongside the due amount in the notification and the reminder bell/list, so a follow-up isn't just a bare amount with no context.", max_length=200),
        ),
    ]
