# Generated by Django 5.2.14 on 2026-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='banking/qr/'),
        ),
    ]
