# Generated by Django 5.2.14 on 2026-07-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_add_qr_code_to_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('IME_PAY', 'IME Pay'), ('MOBILE_BANKING', 'Mobile Banking'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
    ]
