# Generated by Django 5.2.14 on 2026-08-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_update_bankaccount_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('CONNECT_IPS', 'Connect IPS'), ('IME_PAY', 'IME Pay'), ('MOBILE_BANKING', 'Mobile Banking'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
    ]
