# Generated by Django 5.2.14 on 2026-08-21 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_bankaccount_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-created_at']},
        ),
    ]
