# Generated by Django 5.2.14 on 2026-08-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_add_esewa_khalti_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'expense categories'},
        ),
    ]
